Added remove_index
redbooth/rubocop-migrations pull request #1
Opened 2016-09-22 12:52 UTC by magec

# WAT
Adds a check to disallow remove_index
#GIF
![](https://media.giphy.com/media/ToMjGpMhkemTU2YQUjC/giphy.gif)

2016-09-22 13:00 UTC, andresgutgon commented on lib/rubocop/cop/migrations/remove_index.rb
> +      # is used extensively, you could end up with database degradation.
That sounds to me :trollface:

2016-09-22 13:04 UTC, andresgutgon commented on spec/rubocop/cop/migrations/remove_index_spec.rb
> +end
What about testing when `rubocop:disable Migrations/RemoveIndex` comment is there?

2016-09-22 13:09 UTC, magec commented on lib/rubocop/cop/migrations/remove_index.rb
> +      # is used extensively, you could end up with database degradation.
hehe

2016-09-22 13:10 UTC, magec commented on spec/rubocop/cop/migrations/remove_index_spec.rb
> +end
That is part of rubocop code. I have testes it manually and it works, but that functionality is not related with a cop itself, but is about rubocop.

2016-09-22 13:14 UTC, andresgutgon commented on spec/rubocop/cop/migrations/remove_index_spec.rb
> +end
got it

2016-09-22 13:15 UTC, andresgutgon commented
👍

2016-09-22 13:15 UTC, enricostano commented on .rspec
> +--require spec_helper
putting this here has bitten me tons of times, but probably someone else told you that it is awesome :trollface:

2016-09-22 13:19 UTC, enricostano requested changes

2016-09-22 13:19 UTC, enricostano commented
:mailbox_with_no_mail: :+1:

2016-09-22 14:42 UTC, sauloperez commented on lib/rubocop/cop/migrations/remove_index.rb
> +      # is used extensively, you could end up with database degradation.
or simply downtime :trollface:

2016-09-22 14:43 UTC, sauloperez commented on lib/rubocop/cop/migrations/remove_index.rb
> +        MSG = 'remove_index is disalowed'.freeze
s/disalowed/disallowed

2016-09-22 14:44 UTC, sauloperez commented on rubocop-migrations.gemspec
> +  spec.authors       = %w(enricostano magec)
add your name as well

2016-09-22 14:45 UTC, sauloperez commented on rubocop-migrations.gemspec
> +  spec.add_development_dependency 'bundler', '~> 1.11'
I believe the latest is 1.13 something. I would relax it more to be able to use the latest.

2016-09-22 14:47 UTC, sauloperez commented on .rspec
> +--require spec_helper
we don't use it on hosted and I'm not sure it's very common...

2016-09-22 19:07 UTC, franciscoj commented
:clap: :+1:

2016-09-26 09:31 UTC, magec commented on .rspec
> +--require spec_helper
I dropped it but does not show up... wonder why

2016-09-26 09:44 UTC, magec commented on .rspec
> +--require spec_helper
Fixed

2016-09-26 09:46 UTC, sauloperez approved these changes

2016-09-26 09:46 UTC, merged